project:
  type: website
  output-dir: docs

website:
  title: "./cs5805"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      -href: anomaly_detection.ipynb
        text: Anomaly Detection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



