project:
  type: website
  output-dir: docs

website:
  title: "./cs5805"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - anomaly_detection.ipynb
      - classification.ipynb
      - clustering.ipynb
      - probability_theory_and_random_variables.ipynb
      - regression.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



